# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_player_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opponent_team',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default='', max_length=25),
        ),
    ]
